<section id="fixar"><!--/início seção agendamento -->
	<?php
		// Condição que verifica se a requisição retornoou ou não com sucesso
		if(!isset($this->view->dados->success) || $this->view->dados->success != 1){
	?>
		<!-- Div de alerta de erro -->
		<div class="row col-12 bg-danger text-white justify-content-center pt-2 pb-2">
			<a href="/" class="text-white">
				<i class="fa fa-long-arrow-left" aria-hidden="true"></i>
				<span><?php echo $this->view->dados['erro']; ?></span>
			</a>
		</div><!-- Fim div de alerta de erro -->
	<?php
		}else{// Caso o retorno foi com sucesso entra aqui
	?>
			<!--/H1 informa quantidade de profissional encontrado-->
			<div class="container row bg-white m-auto p-4">
				<h3 class="row col-12 mb-5">Preencha seus dados</h3>
				<!--/Envia dados do profissional e os dados do paciente via ajax e guarda no banco de dados-->
				<form  class="row col-8 mt-2" action="/agendamento" method="post">
					<input type="hidden" class="input-group-append" name="specialty_id" value="<?php echo $_POST['specialty_id']; ?>">
					<input type="hidden" class="input-group-append" name="professional_id" value="<?php echo $_POST['professional_id']; ?>">
					<div class="form-group form-inline"><!--/Div que agrupa dois elementos -->
						<input type="text" class="input-group-append form-control form-control-lg ml-4 mr-4 mb-4 bg-select" placeholder="Nome completo" name="name" required>
						<select name="source_id" class="form-control form-control-lg ml-4 mb-4 bg-select">
							<option>Como conheceu?</option>
							<?php
								// Carrega dados de Como conheceu vindo da requisição ajax
								for ($i = 0; $i < count($this->view->dados->content); $i++) {
							?>	
									<option value="<?php echo $this->view->dados->content[$i]->origem_id; ?>">
										<?php echo $this->view->dados->content[$i]->nome_origem; ?>
									</option>
							<?php
								}
							?>
						</select>
					</div><!--/Fim div que agrupa dois elementos -->
					<div class="form-group form-inline"><!--/Div que agrupa dois elementos -->
						<input type="date" class="input-group-append form-control form-control-lg ml-4 mr-4 mb-4 bg-select" placeholder="Nascimento" pattern="[0-9]{4}-[0-9]{2}-[0-9]{2}" name="birthdate" required>
						<input type="number" class="input-group-append form-control form-control-lg ml-4 mb-4 bg-select" placeholder="CPF" name="cpf" required>
					</div><!--/Fim div que agrupa dois elementos -->
					<div class="row col-12 justify-content-end"><!--/Div que contém botão submit-->
						<div class="input-group-append">
							<button type="submit" class="btn btn-verde pl-4 pr-4">SOLICITAR HORÁRIOS</button>
						</div>
					</div><!--/Fim div que contém botão submit-->
				</form>
			</div>
	<?php
		}
	?>
</section>