<section id="fixar"><!--/início seção resposta de agendamento do paciente -->

    <div class="container"><!-- Toda área do conteúdo da página -->
      <div class="row"><!-- Div que alinha conteúdo -->
        <div class="col-lg-12 d-flex bg-transparencia"><!-- Início de Textos da seção -->
          <div class="align-self-center"><!--/Alinhamento do texto-->
          	<h3 class="p-4">Olá, Airton</h3>
            <h1 class="display-4 col-12 ">Seus dados foram salvos</h1>
            <p class="row col-7 text-center p-4">
              Atendendo a mais de 1 milhão de pessoas, a VitalLife é uma clinica que facilita o seu agendamento e por isso estamos atendendo 24h online.
            </p>
         </div>
	</div>
	</div>
</section>