<section id="fixar"><!--/início seção profissional -->
	<?php
		// Condição que verifica se a requisição retornoou ou não com sucesso
		if(!isset($this->view->dados->success) || $this->view->dados->success != 1){
	?>
		<!-- Div de alerta de erro -->
		<div class="row col-12 bg-danger text-white justify-content-center pt-2 pb-2">
			<a href="" class="text-white">
				<i class="fa fa-long-arrow-left" aria-hidden="true"></i>
				<span>Algo deu errado! Tente novamente mais tarde!</span>
			</a>
		</div><!-- Fim div de alerta de erro -->
	<?php
		}else{// Caso o retorno foi com sucesso entra aqui
	?>
		<!--/H1 informa quantidade de profissional encontrado-->
		<h1 class="text-center">
			<?php echo $this->view->encontrados; ?>
			<?php echo $this->view->dados->content[0]->especialidades[0]->nome_especialidade; ?>
			encontrado
		</h1><!--/Fim h1 informa quantidade de profissional encontrado-->
		<div class="container row bg-white m-auto p-4"><!--/área disponível para até 4 profissionais-->

			<?php
				// Rnderiza os dados dos profissionais
				for ($i = 0; $i < count($this->view->dados->content); $i++) {
			?>	
					<!--/Envia dados do profissional para a rota do formulário de agendamento-->
					<form  class="d-flex col-lg-6 justify-content-center mb-4" action="/source" method="post">
						<!--/Div que contém dados do profissional-->
						<div class="row input-group input-group-lg col-10 pt-4 pb-4 justify-content-center shadow raio">
							<input type="hidden" class="input-group-append" name="specialty_id" value="<?php echo $this->view->dados->content[$i]->especialidades[0]->especialidade_id; ?>">
							<input type="hidden" class="input-group-append" name="professional_id" value="<?php echo $this->view->dados->content[$i]->profissional_id; ?>">
							<!--/Div que contém a foto do profissional-->
							<div class="row align-self-start col-3 ">
								<img class="rounded-circle" src="<?php echo $this->view->dados->content[$i]->foto; ?>" width="70" height="70" alt="Profissional">
							</div><!--/Fim div que contém a foto do profissional-->
							<div class="row col-9"><!--/Div que contém dados do profissional-->
								<div class="col-12"><!--/Div que contém nome do profissional-->
									<h4>
										<?php echo $this->view->dados->content[$i]->tratamento; ?>
										<?php echo $this->view->dados->content[$i]->nome; ?>
									</h4>
									<p>
										<?php echo $this->view->dados->content[$i]->conselho; ?>&nbsp
										<?php echo $this->view->dados->content[$i]->documento_conselho; ?>
										</p>
								</div><!--/Fim div que contém nome do profissional-->
								<div class="col-12 pl-4"><!--/Div que contém botão submit-->
									<div class="input-group-append">
										<button type="submit" class="btn btn-verde pl-4 pr-4">AGENDAR</button>
									</div>
								</div><!--/Fim div que contém botão submit-->
							</div><!--/Fim div que contém dados do profissional-->
						</div><!--/ Fim div que contém dados do profissional-->
					</form>	<!--/ fim do form que envia dados do profissional para a rota do formulário de agendamento-->
			<?php
				}
			?>
		</div>
	<?php
		}
	?>
</section><!--/fim seção profissional -->