    <footer class="mt-4 mb-4">
		<div class="container">
			<div class="row">
				<div class="col-md-12 d-flex justify-content-end">
					<a href="" class="btn btn-outline-dark">
				  		<i class="fab fa-facebook cor-style"></i>
					</a>
					<a href="" class="btn btn-outline-dark ml-2">
				  		<i class="fab fa-twitter cor-style"></i>
					</a>
					<a href="" class="btn btn-outline-dark ml-2">
				  		<i class="fab fa-instagram cor-style"></i>
					</a>
					<a href="" class="btn btn-outline-dark ml-2">
				  		<i class="fab fa-youtube cor-style"></i>
					</a>
				</div>
			</div>
		</div>
		</footer>

		<script src="../../vendor/components/jquery/jquery.min.js"></script>
	    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	    <script src="../../vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
</body>
</html>