<!DOCTYPE html>
<html>
<head>
	<title>VitalLife</title>
		<meta content="text/html" charset="utf-8" http-equiv="Content-Type">
    	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    	<link rel="icon" href="../../src/img/site/ico.png" />
		<link rel="stylesheet" href="../../vendor/twbs/bootstrap/dist/css/bootstrap.min.css">
		<script src="https://kit.fontawesome.com/1a758afe82.js" crossorigin="anonymous"></script>
		<link href="../../src/css/style.css" type="text/css" rel="stylesheet" />

<body>
    <header><!-- inicio Cabecalho -->
      <nav class="navbar navbar-expand-sm navbar-light navbar-transparente">
        <div class="container">
          
          <a href="/" class="navbar-brand">
            <img src="../../src/img/site/logo.png" width="250">
          </a>

          <button class="navbar-toggler" data-toggle="collapse" data-target="#nav-principal">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="nav-principal">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                <a href="/" class="nav-link">Home</a>
              </li>
              <li class="nav-item">
                <a href="#" class="btn btn-outline-light ml-4">Entrar</a>
              </li>
            </ul>
          </div>

        </div>
      </nav>
    </header><!--/fim Cabecalho -->